name: comprei_some_ia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.5
  provider: ^6.1.5+1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^17.1.2
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.3
  permission_handler: ^12.0.1
  vibration: ^3.1.4
  url_launcher: ^6.3.2
  animate_do: ^4.2.0
  flutter_animate: ^4.5.2
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
